name: eetu_portfolio
description: Eetu Kallioniemi Portfolio built with Jaspr
version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

jaspr:
  mode: static

dependencies:
  jaspr: ^0.22.0
  jaspr_localizations: ^1.0.0+beta.4
  

dev_dependencies:
  build_runner: ^2.4.10
  jaspr_builder: ^0.22.2
  jaspr_cli: ^0.22.2
  lints: ^3.0.0